import os

SECRET_FOR_GENERATE_TOKEN = os.environ['SECRET_FOR_GENERATE_TOKEN']

MONGO_USERNAME = os.environ['MONGO_USERNAME']
MONGO_PASSWORD = os.environ['MONGO_PASSWORD']
MONGO_DATABASE = os.environ['MONGO_DATABASE']
MONGO_HOSTNAME = os.environ['MONGO_HOSTNAME']

MONGO_HOST = 'mongodb://{}:{}@{}:27017/{}'.format(MONGO_USERNAME, MONGO_PASSWORD, MONGO_HOSTNAME, MONGO_DATABASE)

REDIS_HOST = 'redis'
REDIS_PORT =  6379

SECRET_FOR_CRYPT_PASSWORDS = os.environ['SECRET_FOR_CRYPT_PASSWORDS']